# Generated by Django 5.0 on 2023-12-26 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_productview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='your_model',
            new_name='product',
        ),
    ]
