# Generated by Django 5.0 on 2023-12-31 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_order_donation_order_email_order_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='donation',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
