# Generated by Django 5.0 on 2023-12-31 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_order_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam voluptatem itaque dignissimos eum cupiditate repudiandae molestias error consequatur inventore illum. Maxime sit laborum nulla cumque, inventore quidem quo odio nam? Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam qui quod blanditiis sint maxime magnam autem vero reprehenderit porro delectus quasi neque, praesentium repellat voluptatum repudiandae ipsum ad, impedit fuga.'),
            preserve_default=False,
        ),
    ]
