# Generated by Django 5.0 on 2024-01-02 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_order_user_id_season_active_season_add_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='contacts',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
