# Generated by Django 5.0 on 2024-01-04 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_season_markup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='active',
        ),
        migrations.AlterField(
            model_name='season',
            name='sales_date_start',
            field=models.DateField(),
        ),
    ]
