# Generated by Django 5.0 on 2024-01-07 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0013_order_open"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="season",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="base.season"
            ),
            preserve_default=False,
        ),
    ]
