# Generated by Django 5.0 on 2024-03-08 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0014_order_season"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="quantity_in_stalk",
            new_name="quantity_in_stock",
        ),
    ]
