# Generated by Django 5.0.9 on 2024-11-30 18:25

import base.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_productimage_image_productvariation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='group_members',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='name',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='production_cost',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='season',
        ),
        migrations.AddField(
            model_name='productvariation',
            name='varient_label',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_members', models.JSONField()),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to=base.models.image_upload)),
                ('production_cost', models.FloatField()),
                ('description', models.TextField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.season')),
            ],
        ),
        migrations.AddField(
            model_name='productvariation',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.product'),
            preserve_default=False,
        ),
    ]
