# Generated by Django 5.0.9 on 2024-12-02 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_rename_varient_label_productvariation_variant_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='product',
            new_name='variation',
        ),
    ]
