# Generated by Django 5.0.9 on 2024-12-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_rename_product_productimage_variation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='student_deliverer',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_instructions',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
